export const REGIOES = ["norte", "nordeste", "centro-oeste", "sudeste", "sul"] as const;
export type Regiao = (typeof REGIOES)[number];

export const NOME_REGIAO: Record<Regiao, string> = {
  norte: "Norte",
  nordeste: "Nordeste",
  "centro-oeste": "Centro-Oeste",
  sudeste: "Sudeste",
  sul: "Sul",
};

export const UF_PARA_REGIAO: Record<string, Regiao> = {
  AC: "norte",
  AP: "norte",
  AM: "norte",
  PA: "norte",
  RO: "norte",
  RR: "norte",
  TO: "norte",
  AL: "nordeste",
  BA: "nordeste",
  CE: "nordeste",
  MA: "nordeste",
  PB: "nordeste",
  PE: "nordeste",
  PI: "nordeste",
  RN: "nordeste",
  SE: "nordeste",
  DF: "centro-oeste",
  GO: "centro-oeste",
  MT: "centro-oeste",
  MS: "centro-oeste",
  ES: "sudeste",
  MG: "sudeste",
  RJ: "sudeste",
  SP: "sudeste",
  PR: "sul",
  RS: "sul",
  SC: "sul",
};

export const NOME_ESTADO: Record<string, string> = {
  AC: "Acre",
  AP: "Amapá",
  AM: "Amazonas",
  PA: "Pará",
  RO: "Rondônia",
  RR: "Roraima",
  TO: "Tocantins",
  AL: "Alagoas",
  BA: "Bahia",
  CE: "Ceará",
  MA: "Maranhão",
  PB: "Paraíba",
  PE: "Pernambuco",
  PI: "Piauí",
  RN: "Rio Grande do Norte",
  SE: "Sergipe",
  DF: "Distrito Federal",
  GO: "Goiás",
  MT: "Mato Grosso",
  MS: "Mato Grosso do Sul",
  ES: "Espírito Santo",
  MG: "Minas Gerais",
  RJ: "Rio de Janeiro",
  SP: "São Paulo",
  PR: "Paraná",
  RS: "Rio Grande do Sul",
  SC: "Santa Catarina",
};
